### ISSUE TITLE
Info window pops up on camera move

### ISSUE THREAD

**Issue by Apollo108** [abhishekduhoon/custom_info_window#1]
Hi, thank you for the package, but I have one issue - info window constantly pops up on camera move, despite being hidden by onTap() before. It seems to me that it's abnormal behaviour, do you have any thoughts on how to fix that?

**Comment by Apollo108** [comment]
![image](https://user-images.githubusercontent.com/16933202/107746739-fdd56800-6d1e-11eb-8373-ef74d25d4483.png)
I have already fixed it - you can update the package, if this is correct answer)

**Comment by abhishekduhoon** [comment]
> Hi, thank you for the package, but I have one issue - info window constantly pops up on camera move, despite being hidden by onTap() before. It seems to me that it's abnormal behaviour, do you have any thoughts on how to fix that?

Thanks @Apollo108 for pointing out this issue. I have updated the package as per your solution.
