### ISSUE TITLE
it does not support web 

### ISSUE THREAD

**Issue by mufarrah** [abhishekduhoon/custom_info_window#11]
I will really like to use this package for web, could that be implemented ??

**Comment by Babwenbiber** [comment]
This package is very small.
You might copy the code and put it into your app directly.
Then replace import `'dart:io';` with `import 'package:universal_io/io.dart';` and import universal_io into your pubspec

**Comment by M3gar00** [comment]
I opened a [PR](https://github.com/abhishekduhoon/custom_info_window/pull/15) that fixes this problem. With any luck it'll be accepted and merged.
