### ISSUE TITLE
Change the height and width of CustomInfoWindow according to the content

### ISSUE THREAD

**Issue by andyli0123** [abhishekduhoon/custom_info_window#16]
```dart
CustomInfoWindow(
  controller: _customInfoWindowController,
  height: 55, // dynamic
  width: 160, // dynamic
  offset: 50,
),
```
How to implement change the height and width of CustomInfoWindow according to the content?

**Comment by MFaulk13** [comment]
Created a fork that supports it: [fork](https://github.com/MFaulk13/custom_info_window) and a PR

**Comment by andynewman10** [comment]
@MFaulk13 unless I'm mistaken, your fork does not support his. With your fork, we still need to give an explicit (not dynamically-calculated) height and width for the contents.
What we should have is to NOT have to specify an explicit width and height, and the info window needs to adjust its size based on the size of its contents (buttons, images...).
I wonder if this cannot be done with the MeasureSize widget, but I'm not an expert.

**Comment by MFaulk13** [comment]
Hi @andynewman10 
How I achieve it in my project is that in the iterations over all the markers i create i can now set a specific width and height for that concerning addInfoWindow call, which was sufficient as I here controll the size of the widget.
However I do agree that its not adjusted automatically depending on the size of the widget, but this was not the scope of my change.
I'm not sure how this could be done, maybe with a fixed width you could use the IntrinsicHeight class, however from the documentation, this class is relatively expensive.
As I understand the MeasureSize widget, it measures the size of a child widget after it has been rendered, i'm not sure this will work.
