### ISSUE TITLE
i cant upgrade google_maps flutter 

### ISSUE THREAD

**Issue by iamir4g** [abhishekduhoon/custom_info_window#3]
hi, thank you for the practical package.
i want to update a new version of  google_maps_flutter version 2 (2.0.2)but get this error :
Because custom_info_window 0.0.4 depends on google_maps_flutter ^1.1.1 and no versions of custom_info_window match >0.0.4 <0.1.0, custom_info_window ^0.0.4 requires google_maps_flutter ^1.1.1.
So, because irantracking(my app name) depends on both google_maps_flutter ^2.0.2 and custom_info_window ^0.0.4, version solving failed.
pub get failed (1; So, because irantracking(my app name) depends on both google_maps_flutter ^2.0.2 and custom_info_window ^0.0.4, version solving failed.)

**Comment by abhishekduhoon** [comment]
hi @iamir4g, can you please tell me the flutter version you are using? Also whether are you using null safety?

**Comment by iamir4g** [comment]
> hi @iamir4g, can you please tell me the flutter version you are using? Also whether are you using null safety?

thank, this is my `flutter doctor`:
[✓] Flutter (Channel stable, 2.0.4, on macOS 11.2.2 20D80 darwin-x64, locale en-IR)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.55.0)
[✓] Connected device (2 available)

**Comment by abhishekduhoon** [comment]
I have migrated the package to null safety. Please use "custom_info_window: ^1.0.0" in your pubspec.yaml and update me how it goes.

**Comment by iamir4g** [comment]
> use "custom_info

thank a lot,

**Comment by abhishekduhoon** [comment]
This is related to google_maps_flutter. Also this is not an error so ignore this. I am closing this issue now.
