### ISSUE TITLE
Widget disappears when touching left or top of screen

### ISSUE THREAD

**Issue by xapatjb4** [abhishekduhoon/custom_info_window#4]
Hello!

As the title states, when moving camera to bring widget offscreen from top or left, it disappears and the leftmost/topmost part of the widget touches edge of screen.

This does not occur for bottom and right side of screen

P.S. Thanks for turning this into a package, save a lot of time from having to make a custom info window

**Comment by abhishekduhoon** [comment]
Hi @xapatjb4,

Thanks for creating this issue. Before creating this package I was using different approach to solve this in my personal project which involved container with margins. As containers can not have negative margins so I have to hide the info window when approaching left or top of the screen. This package uses positioned widget which can handle negative coordinates but I forgot to remove the condition which was making the info window disappear. Now i have updated the package so please use custom_info_window: ^1.0.1 in your pubspec.yaml.

Please update here if its working now.

**Comment by xapatjb4** [comment]
Works like a charm!! Thanks for the prompt fix
