### ISSUE TITLE
possible info_window always open without Tap any screen?

### ISSUE THREAD

**Issue by anwar907** [abhishekduhoon/custom_info_window#5]
when maps open, info_window always open without Tap other screen like position and other, how about you with this problem in flutter?

**Comment by abhishekduhoon** [comment]
@anwar907 sorry for late response. So you want to show info window without tap or any other user interaction. Right?

**Comment by anwar907** [comment]
> @anwar907 sorry for late response. So you want to show info window without tap or any other user interaction. Right?

yes right, it's possible in google maps flutter? or do you have try custom info window when you open app, many info window auto open without Tap?

**Comment by anthracite-abhishek** [comment]
Hey @anwar907, at present this feature is not present in this package. This only supports single info window. However you can open an info window without any tap. To do this you just need to call  addInfoWindow from _customInfoWindowController object.

**Comment by anwar907** [comment]
> Hey @anwar907, at present this feature is not present in this package. This only supports single info window. However you can open an info window without any tap. To do this you just need to call addInfoWindow from _customInfoWindowController object.

I have explore for function `addInfoWindow` but in flutter now can't support about that, do you have example code for addInfoWindow  and work until now?

**Comment by abhishekduhoon** [comment]
@anwar907 , Please go through https://github.com/abhishekduhoon/custom_info_window/blob/master/example/main.dart

**Comment by anwar907** [comment]
> @anwar907 , Please go through https://github.com/abhishekduhoon/custom_info_window/blob/master/example/main.dart

thank you for your question, for this issues I have solve with convert Canvas to Image and this is the result

![Screen Shot 2021-07-25 at 01 12 22](https://user-images.githubusercontent.com/35429445/126877575-0699367f-25a3-43df-96ad-154eb74d7d8c.png)

**Comment by speedlightwp** [comment]
We have showMarkerInfoWindow(Marker Id), to display the infoWindow without tapping it. Can it be done for custom_info_window?
